# cs
    
server:
  port: 10001

spring:
  application:
    name: cdm
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://45.76.205.204:14306/cs?characterEncoding=utf8&useUnicode=true&useLegacyDatetimeCode=false&useTimezone=true&serverTimezone=GMT%2B8&autoReconnect=true&useSSL=false&useServerPrepStmts=true&allowMultiQueries=true
    username: csroot
    password: csroot
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 
    pool.max-active: 8
    pool.max-wait: -1
    pool.max-idle: 8
    pool.min-idle: 0
    timeout: 2000
  # mvc:
  #   view:
  #     prefix: /jsp/
  #     suffix: .jsp

mybatis:
  type-aliases-package: demo.base.user.pojo
  configuration:
    map-underscore-to-camel-case: true
    
logging:
  level:
    # demo.test.mapper: DEBUG
    # demo.tool.mapper: DEBUG
    # demo.mapper: DEBUG
     demo.base.base.mapper: DEBUG
     demo.base.user.mapper: DEBUG
